- hosts: all
  connection: local
  user: user
  sudo: false
  gather_facts: false
  serial: 1
  vars:
    ansible_connection: local

  tasks:
  - name: delete servers and clients
    vsphere_guest:
      vcenter_hostname: 192.168.1.210
      username: Administrator
      password: I@R@nge!
      guest: "{{ inventory_hostname_short }}"
      state: absent
      force: yes