---
- name: change hostname
  win_hostname: name="{{inventory_hostname_short}}" restart=yes
  
#- name: Pause for 1 Minute 
#  pause: seconds=60
  
- name: Wait for computer to reboot
  local_action: wait_for host={{ansible_ssh_host}} timeout=600
                port={{ansible_ssh_port}} state=started
                delay=30