---
- name: change hostname
  win_hostname: name="{{inventory_hostname_short}}" restart=no
  
#TODO: Currently Causes a Reboot on every run. Need some conditionals in the Playbook.
- name: Reboot Computer
  raw: powershell.exe -Command Restart-Computer -Force
  
- name: Wait for computer to reboot
  local_action: wait_for host={{ansible_ssh_host}} timeout=600
                port={{ansible_ssh_port}} state=started
                delay=30